"""Add project Section details

Revision ID: 462be6cd5500
Revises: c86858cb3342
Create Date: 2020-10-06 11:23:21.808646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462be6cd5500'
down_revision = 'c86858cb3342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_section', sa.Column('image_1', sa.String(length=255), nullable=True))
    op.add_column('project_section', sa.Column('image_2', sa.String(length=255), nullable=True))
    op.add_column('project_section', sa.Column('image_3', sa.String(length=255), nullable=True))
    op.add_column('project_section', sa.Column('paragraph', sa.Text(), nullable=True))
    op.add_column('project_section', sa.Column('title', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_section', 'title')
    op.drop_column('project_section', 'paragraph')
    op.drop_column('project_section', 'image_3')
    op.drop_column('project_section', 'image_2')
    op.drop_column('project_section', 'image_1')
    # ### end Alembic commands ###
