"""Add social media table

Revision ID: 5ee6d2f2bcae
Revises: 99cf082b08f6
Create Date: 2020-10-06 22:27:22.816564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ee6d2f2bcae'
down_revision = '99cf082b08f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_media_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('display', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_media_link')
    # ### end Alembic commands ###
