"""empty message

Revision ID: a30e2fc5d0d4
Revises: 462be6cd5500
Create Date: 2020-10-06 20:21:49.333182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a30e2fc5d0d4'
down_revision = '462be6cd5500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('static_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('headline_work', sa.String(length=255), nullable=True),
    sa.Column('subline_work', sa.Text(), nullable=True),
    sa.Column('cover_image_work', sa.String(length=64), nullable=True),
    sa.Column('headline_about', sa.String(length=255), nullable=True),
    sa.Column('subline_about', sa.Text(), nullable=True),
    sa.Column('paragraph_about', sa.Text(), nullable=True),
    sa.Column('headline_contact', sa.String(length=255), nullable=True),
    sa.Column('subline_contact', sa.Text(), nullable=True),
    sa.Column('image_contact', sa.String(length=64), nullable=True),
    sa.Column('headline_experiments', sa.String(length=255), nullable=True),
    sa.Column('subline_experiments', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('static_elements')
    # ### end Alembic commands ###
