"""Remove html column

Revision ID: c86858cb3342
Revises: c9de6229e801
Create Date: 2020-10-06 11:20:11.854600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c86858cb3342'
down_revision = 'c9de6229e801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_section') as batch_op:
       batch_op.drop_column('html')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_section', sa.Column('html', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
