"""add url_name column

Revision ID: c9de6229e801
Revises: 7dff87780855
Create Date: 2020-10-05 20:28:20.284879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9de6229e801'
down_revision = '7dff87780855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('url_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'url_name')
    # ### end Alembic commands ###
